/*******************************************************************************
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 *
 *     You should have received a copy of the GNU General Public License
 *     along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *******************************************************************************/
package org.worldgrower.gui;

public enum ImageIds {
	KNIGHT,
	GUARD,
	BUCKET,
	BUSH,
	GOBLIN,
	TRUNK,
	TREE,
	SHACK,
	FEMALE_COMMONER,
	WELL,
	SKELETON,
	ORC_SOLDIER,
	STONE_RESOURCE,
	ORE_RESOURCE,
	HOUSE,
	SMITH,
	BLUE_HAIRED_COMMONER,
	TULBAN_MALE_COMMONER,
	GREEN_HAIRED_COMMONER,
	MALE_SCIENTIST_COMMONER,
	BLACK_HAIRED_FEMALE_COMMONER,
	GREEN_HAIRED_MALE_BOY,
	GREEN_HAIRED_MALE_COMMONER,
	PURPLE_HAIRED_MALE_GIRL,
	PURPLE_HAIRED_MALE_COMMONER,
	PURPLE_HAT_COMMONER,
	GREY_HAIRED_MALE_COMMONER,
	PINK_HAT_FEMALE_COMMONER,
	RED_HAIR_FEMALE_COMMONER,
	BLUE_HAT_MALE_COMMONER,
	FEMALE_NUN_COMMONER,
	BOLD_MALE_COMMONER,
	MALE_CHEF_COMMONER,
	SPIKY_HAIR_MALE_COMMONER,
	GREY_HAIR_MALE_COMMONER,
	BLUE_DRESS_FEMALE_COMMONER,
	MALE_BAKER_COMMONER,
	STATUE_OF_DEITY,
	GREEN_HAIR_MALE_COMMONER,
	MALE_SAGE_COMMONER,
	MALE_MERCHANT_COMMONER,
	MALE_CAPTAIN_COMMONER,
	ORANGE_HAIR_BOY_COMMONER,
	TULBAN_BOY_COMMONER,
	SKINHEAD_BOY_COMMONER,
	FEMALE_BRIDE_COMMONER,
	RAT,
	SLIME,
	IRON_CLAYMORE,
	IRON_CUIRASS,
	SPIDER,
	COCOON,
	GRAVE,
	GRAPE_VINE,
	IRON_HELMET,
	IRON_GAUNTLETS,
	IRON_BOOTS,
	LONGBOW,
	MALE_LEADER,
    MALE_SENATOR,
    FEMALE_SENATOR,
    FEMALE_RED_EYE,
    FEMALE_BUNNY,
    MALE_BELLBOY,
    MALE_LAWYER,
    FEMALE_MAID,
    BERRY,
    MALE_SAILOR,
    MALE_WHITE_SHIRT_SAILOR,
    MALE_BLOND_SAILOR,
    FEMALE_RED_HAIRED_SAILOR,
    GRAPES,
    WOOD,
    IRON,
    STONE,
    GOLD_RESOURCE,
    GOLD,
    WINE,
    MALE_CAPTAIN,
    FEMALE_SAILOR,
    MALE_BALD_SAILOR,
    MALE_GREEN_BANDANA_SAILOR,
    PAPER,
    PAPER_MILL,
    WATER,
    MALE_BALD_COMMONER,
    FEMALE_OLD_COMMONER,
    MALE_BEARDED_COMMONER,
    FEMALE_BLOND_COMMONER,
    YOUNG_BOY_COMMONER,
    FEMALE_ORANGE_GIRL,
    MALE_BLUE_PANTS_BOY_COMMONER,
    FEMALE_ORANGE_HAIR_GIRL_COMMONER,
    BLACK_CROSS,
	MALE_OLD_COMMONER,
	FEMALE_OLDER_COMMONER,
	MALE_SPIKY_HAIRED_COMMONER,
	FEMALE_MILKER_COMMONER,
	MALE_GREEN_HAIRED_COMMONER,
	FEMALE_BLOND_GIRL,
	MALE_BROWN_HAIR_BOY_COMMONER,
	FEMALE_BLUE_HAIR_GIRL_COMMONER,
	LIBRARY,
	BURNING,
	SPELL_BOOK
}
